### ISSUE TITLE
В чому ідея даної організації?

### ISSUE THREAD

**Issue by funivan** [replace-org-ua/invites#2]

**Comment by leofun01** [comment]
Ідея в тому, що кожен учасник може створити дискусію (або issue) з проханням зробити review. Можна робити дискусії загальні для всіх, а можна і для конкретних користувачів.
І ви маєте можливість створювати підгрупи.

І найголовніше:
В інших місцях GitHub'а спілкування не англійською мовою вважається поганим тоном. А тут можна спілкуватися українською.
