### ISSUE TITLE
Вітаю

### ISSUE THREAD

**Issue by leon-mbs** [replace-org-ua/invites#3]
Хочу долучитися до спільности.
Я вже зареєстрован(ий|а) на форумі replace.org.ua,
ім'я користувача :

**Comment by leofun01** [comment]
@leon-mbs ви забули дописати ім'я користувача.

**Comment by leon-mbs** [comment]
Caballero

**Comment by leofun01** [comment]
Ок. Запрошення відправлене на пошту.
