### ISSUE TITLE
Issue - should be Invitation!!! [Xackspel]

### ISSUE THREAD

**Issue by Xackspel** [replace-org-ua/invites#6]
Хочу долучитися до спільности.
Я вже зареєстрован(ий|а) на форумі replace.org.ua,
ім'я користувача : Xackspel

Додречі правильно буде Invitation а не Invites!

**Comment by leofun01** [comment]
Запрошення відправлено вам на пошту.

---
> Додречі правильно буде Invitation а не Invites!

Я би так і назвав, якби англомовці називали це Invitation а не Invites.
