### ISSUE TITLE
Вітаю

### ISSUE THREAD

**Issue by iboldurev** [replace-org-ua/invites#8]
Хочу долучитися до спільности.
Я вже зареєстрован(ий|а) на форумі replace.org.ua,
ім'я користувача : iboldurev

**Comment by leofun01** [comment]
Запрошення відправлено.

**Comment by leofun01** [comment]
А ще у вас у профілі на GitHub висить застаріле посилання `http://iboldurev.com`.

**Comment by iboldurev** [comment]
Дякую, так забув продовжити
