### ISSUE TITLE
Вітаю

### ISSUE THREAD

**Issue by timofiy** [replace-org-ua/invites#9]
Хочу долучитися до спільности.
Я вже зареєстрован(ий|а) на форумі replace.org.ua,
ім'я користувача :tim 
https://github.com/timofiy

**Comment by leofun01** [comment]
Запрошення відправлено.

**Comment by leofun01** [comment]
Відправив запрошення ще раз. Якщо у вас виникли проблеми з цим, допишіть сюди коментар з описом.
